USE [master]
GO
CREATE DATABASE [MVCCRUD] ON  PRIMARY 
( NAME = N'MVCCRUD', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MVCCRUD.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MVCCRUD_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MVCCRUD_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MVCCRUD] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVCCRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MVCCRUD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MVCCRUD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MVCCRUD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MVCCRUD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MVCCRUD] SET ARITHABORT OFF 
GO
ALTER DATABASE [MVCCRUD] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MVCCRUD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MVCCRUD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MVCCRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MVCCRUD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MVCCRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MVCCRUD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MVCCRUD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MVCCRUD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MVCCRUD] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MVCCRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MVCCRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MVCCRUD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MVCCRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MVCCRUD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MVCCRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MVCCRUD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MVCCRUD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MVCCRUD] SET  MULTI_USER 
GO
ALTER DATABASE [MVCCRUD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MVCCRUD] SET DB_CHAINING OFF 
GO
USE [MVCCRUD]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Fecha] [date] NULL,
	[Clave] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Usuarios] ON 

INSERT [dbo].[Usuarios] ([id], [Nombre], [Fecha], [Clave]) VALUES (1, N'Wilmer', CAST(N'1994-06-24' AS Date), N'123456')
INSERT [dbo].[Usuarios] ([id], [Nombre], [Fecha], [Clave]) VALUES (2, N'Andy', CAST(N'2020-11-27' AS Date), N'1234')
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
GO
USE [master]
GO
ALTER DATABASE [MVCCRUD] SET  READ_WRITE 
GO
